image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  
check:
  stage: test
  script:
    - 'dotnet build ./NetSorter'
    - 'dotnet build ./NetSorterTest'
    - 'dotnet test ./NetSorterTest'
    - cd NetSorter
    - dotnet run
    - ls -la ./NetSorter/bin/Debug/net6.0/
    - ./NetSorter/bin/Debug/net6.0/NetSorter

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
