#image: mcr.microsoft.com/dotnet/sdk:latest
image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  
check:
  stage: test
  script:
    - 'dotnet build ./NetSorter'
    - 'dotnet build ./NetSorterTest'
    - 'dotnet test ./NetSorterTest'
    - cd NetSorter
    - dotnet run

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
