image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - test
  
check:
  stage: test
  script:
    - 'dotnet build ./NetSorter'
    - 'dotnet build ./NetSorterTest'
    - 'dotnet test ./NetSorterTest'

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
