image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  
check:
  stage: test
  script:
    - dotnet build ./NetSorter
    - dotnet build ./NetSorterTest
    - dotnet test ./NetSorterTest
    - ls -la ./NetSorter/bin/Debug/net6.0/
    - ./NetSorter/bin/Debug/net6.0/NetSorter

trivy:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
    - ./trivy fs .

# included in test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
