image: mcr.microsoft.com/dotnet/sdk:latest

pipelines:
  default:
    - step:
        name: Check
        script:
          - 'dotnet build ./NetSorter'
          - 'dotnet build ./NetSorterTest'
          - 'dotnet test ./NetSorterTest'
          - cd NetSorter
          - dotnet run


