image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - step:
        name: Check
        script:
          - dotnet build ./NetSorter
          - dotnet build ./NetSorterTest
          - dotnet test ./NetSorterTest
          - ls -la ./NetSorter/bin/Debug/net6.0/
          - ./NetSorter/bin/Debug/net6.0/NetSorter


