name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: dotnet build ./NetSorter
      - run: dotnet build ./NetSorterTest
      - run: dotnet test ./NetSorterTest
      - run: cd NetSorter
      - run: dotnet run
